// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWfuuu8VwxNTjPYnThfW9LV4Byj36-7I',
    appId: '1:985378262660:web:6de1bafa0a78f635d1fcd1',
    messagingSenderId: '985378262660',
    projectId: 'myott-a40db',
    authDomain: 'myott-a40db.firebaseapp.com',
    storageBucket: 'myott-a40db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3hIvKIhNeAvHnySS2fANKkk5EcO-KTkc',
    appId: '1:985378262660:android:ab10509bab8cb5b3d1fcd1',
    messagingSenderId: '985378262660',
    projectId: 'myott-a40db',
    storageBucket: 'myott-a40db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeWfuuu8VwxNTjPYnThfW9LV4Byj36-7I',
    appId: '1:985378262660:ios:...', // Not available in .env.local, needs GoogleService-Info.plist
    messagingSenderId: '985378262660',
    projectId: 'myott-a40db',
    storageBucket: 'myott-a40db.firebasestorage.app',
    iosBundleId: 'com.myott.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeWfuuu8VwxNTjPYnThfW9LV4Byj36-7I',
    appId: '1:985378262660:ios:...', 
    messagingSenderId: '985378262660',
    projectId: 'myott-a40db',
    storageBucket: 'myott-a40db.firebasestorage.app',
    iosBundleId: 'com.myott.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeWfuuu8VwxNTjPYnThfW9LV4Byj36-7I',
    appId: '1:985378262660:web:6de1bafa0a78f635d1fcd1',
    messagingSenderId: '985378262660',
    projectId: 'myott-a40db',
    authDomain: 'myott-a40db.firebaseapp.com',
    storageBucket: 'myott-a40db.firebasestorage.app',
  );
}
